{
 "title": "Druid MiddleManagers",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.middleManager.*.heap.jvm.mem.committed"
    },
    {
     "target": "wakanda.druid.middleManager.*.heap.jvm.mem.used"
    },
    {
     "target": "wakanda.druid.middleManager.*.heap.jvm.mem.max"
    }
   ]
  },
  {
   "title": "Non Heap All",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.middleManager.*.nonheap.*.*.*.*"
    }
   ]
  },
  {
   "title": "Jetty Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.middleManager.*.jetty.numOpenConnections"
    }
   ]
  },
  {
   "title": "Jvm bufferpool",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.middleManager.*.jvm.*.*"
    }
   ]
  },
  {
   "title": "G1 gc",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.middleManager.*.G1_Old_Generation.jvm.*.*"
    },
    {
     "target": "wakanda.druid.middleManager.*.G1_Young_Generation.jvm.*.*"
    }
   ]
  }
 ]
}