{
 "title": "Druid Historical",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Jvm Used/Committed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.historical.*.heap.jvm.mem.used"
    },
    {
     "target": "wakanda.druid.historical.*.heap.jvm.mem.committed"
    }
   ]
  },
  {
   "title": "Jetty Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.historical.*.jetty.numOpenConnections"
    }
   ]
  },
  {
   "title": "Non Heap Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.historical.*.nonheap.*.*.pool.used"
    }
   ]
  },
  {
   "title": "Non Heap Committed/Max",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.historical.*.nonheap.*.*.pool.committed"
    },
    {
     "target": "wakanda.druid.historical.*.nonheap.*.*.pool.max"
    }
   ]
  },
  {
   "title": "Query Metrics per datasource",
   "type": "graph",
   "description": "our datasources have a suffix \"Test\" or \"v1_0\"",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.historical.*.*Test.*.query.*.*"
    },
    {
     "target": "wakanda.druid.historical.*.*v1_0.*.query.*.*"
    }
   ]
  },
  {
   "title": "Segment Metrics per datasource",
   "type": "graph",
   "description": "our datasources have a suffix \"Test\" or \"v1_0\"",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.historical.*.*Test.*.0.segment.*"
    },
    {
     "target": "wakanda.druid.historical.*.*v1_0.*.0.segment.*"
    }
   ]
  },
  {
   "title": "Segment",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.historical.*.segment.*.*"
    }
   ]
  },
  {
   "title": "Query metrics",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.historical.*.query.*.*.*"
    }
   ]
  },
  {
   "title": "G1 gc time",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.historical.*.G1_Old_Generation.jvm.gc.time"
    },
    {
     "target": "wakanda.druid.historical.*.G1_Young_Generation.jvm.gc.time"
    }
   ]
  },
  {
   "title": "G1 gc count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.historical.*.G1_Old_Generation.jvm.gc.count"
    },
    {
     "target": "wakanda.druid.historical.*.G1_Young_Generation.jvm.gc.count"
    }
   ]
  },
  {
   "title": "Jvm Spaces Committed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.historical.*.heap.G1_Eden_Space.jvm.pool.committed"
    },
    {
     "target": "wakanda.druid.historical.*.heap.G1_Old_Gen.jvm.pool.committed"
    },
    {
     "target": "wakanda.druid.historical.*.heap.G1_Survivor_Space.jvm.pool.committed"
    }
   ]
  },
  {
   "title": "Jvm Spaces Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.historical.*.heap.G1_Eden_Space.jvm.pool.used"
    },
    {
     "target": "wakanda.druid.historical.*.heap.G1_Old_Gen.jvm.pool.used"
    },
    {
     "target": "wakanda.druid.historical.*.heap.G1_Survivor_Space.jvm.pool.used"
    }
   ]
  }
 ]
}