{
 "title": "Druid Overlord",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "G1 gc",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.overlord.*.G1_Old_Generation.jvm.gc.*"
    },
    {
     "target": "wakanda.druid.overlord.*.G1_Young_Generation.jvm.gc.*"
    }
   ]
  },
  {
   "title": "heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.overlord.*.heap.jvm.mem.committed"
    },
    {
     "target": "wakanda.druid.overlord.*.heap.jvm.mem.used"
    }
   ]
  },
  {
   "title": "non heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.overlord.*.nonheap.jvm.mem.committed"
    },
    {
     "target": "wakanda.druid.overlord.*.nonheap.jvm.mem.used"
    }
   ]
  },
  {
   "title": "jetty connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.overlord.*.jetty.numOpenConnections"
    }
   ]
  },
  {
   "title": "jvm bufferpool",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.overlord.*.jvm.bufferpool.*"
    }
   ]
  }
 ]
}