{
 "title": "Druid Coordinators",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Jetty NumConnections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.coordinator.*.jetty.numOpenConnections"
    }
   ]
  },
  {
   "title": "Jvm BufferPool",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.coordinator.*.jvm.*.*"
    }
   ]
  },
  {
   "title": "Default_tier_segments",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.coordinator.*._default_tier.segment.*.count"
    }
   ]
  },
  {
   "title": "Jvm Heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.coordinator.*.heap.*.*.committed"
    },
    {
     "target": "wakanda.druid.coordinator.*.heap.*.*.used"
    },
    {
     "target": "wakanda.druid.coordinator.*.heap.*.*.pool.committed"
    },
    {
     "target": "wakanda.druid.coordinator.*.heap.*.*.pool.used"
    }
   ]
  },
  {
   "title": "Segment*",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.coordinator.*.segment.*.count"
    }
   ]
  },
  {
   "title": "Jvm Non-Heap",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.coordinator.*.nonheap.*.*.committed"
    },
    {
     "target": "wakanda.druid.coordinator.*.nonheap.*.*.used"
    },
    {
     "target": "wakanda.druid.coordinator.*.nonheap.*.*.pool.committed"
    },
    {
     "target": "wakanda.druid.coordinator.*.nonheap.*.*.pool.used"
    }
   ]
  },
  {
   "title": "Datasources Segment Sizes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.coordinator.*.*vTest.*.size"
    },
    {
     "target": "wakanda.druid.coordinator.*.*v1_0.*.size"
    }
   ]
  },
  {
   "title": "G1 gc",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.coordinator.*.G1*.*.*.*"
    }
   ]
  },
  {
   "title": "Segment Q counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.coordinator.*.*8083.*.*.*"
    }
   ]
  }
 ]
}