{
 "title": "Druid Brokers",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Jetty Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.broker.*.jetty.numOpenConnections"
    }
   ]
  },
  {
   "title": "Heap Mem -  Committed Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.broker.*.heap.*.mem.committed"
    },
    {
     "target": "wakanda.druid.broker.*.heap.*.mem.used"
    }
   ]
  },
  {
   "title": "Heap GenSpaces - Committed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.broker.*.heap.*.jvm.*.committed"
    }
   ]
  },
  {
   "title": "Heap GenSpaces - Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.broker.*.heap.*.jvm.*.used"
    }
   ]
  },
  {
   "title": "G1_GC_Counts",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.broker.*.G1_Old_Generation.jvm.gc.count"
    },
    {
     "target": "wakanda.druid.broker.*.G1_Young_Generation.jvm.gc.count"
    }
   ]
  },
  {
   "title": "G1_GC_times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.broker.*.G1_Young_Generation.jvm.gc.time"
    },
    {
     "target": "wakanda.druid.broker.*.G1_Old_Generation.jvm.gc.time"
    }
   ]
  },
  {
   "title": "Non heap Committed Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.broker.*.nonheap.*.*.committed"
    },
    {
     "target": "wakanda.druid.broker.*.nonheap.*.*.used"
    },
    {
     "target": "wakanda.druid.broker.*.nonheap.*.*.max"
    }
   ]
  },
  {
   "title": "Non heap Pool - Committed Used",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.broker.*.nonheap.*.*.pool.committed"
    },
    {
     "target": "wakanda.druid.broker.*.nonheap.*.*.pool.used"
    },
    {
     "target": "wakanda.druid.broker.*.nonheap.*.*.pool.max"
    }
   ]
  },
  {
   "title": "Query cache",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.broker.*.query.*.*.*"
    }
   ]
  },
  {
   "title": "Segment scans",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.broker.*.segment.*.*"
    }
   ]
  },
  {
   "title": "DataSource Quey Cpu Times",
   "type": "graph",
   "description": "my datasources have a prefixes like v1_0 and vTest , hence the regular expression in metrics",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.broker.*.*_vTest.*.*.*.*"
    },
    {
     "target": "wakanda.druid.broker.*.*v1_0.*.*.*.*"
    }
   ]
  },
  {
   "title": "Server TTfb & node times",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "wakanda.druid.broker.*.*:8083.query.node.time"
    },
    {
     "target": "wakanda.druid.broker.*.*:8083.query.node.ttfb"
    }
   ]
  }
 ]
}